### ISSUE TITLE
pretix import: Support product variations

### ISSUE THREAD

**Issue by rixx** [c3cashdesk/postix#10]
When redeeming an item that had variations in pretix, the cart does not show the item's variation.

**Comment by raphaelm** [comment]
Hmm, as postix know nothing about variations, every variation would need to be imported as a seperate product. Apparently, the current importer even *aborts* when it sees variations: https://github.com/c3cashdesk/postix/blob/master/src/postix/core/management/commands/import_presale.py#L35

...which leads me to the question of how the hell did we do this at last MRMCD with the t-shirt sizes? :D

**Comment by rixx** [comment]
It doesn't abort, it just writes a warning to stdout.

**Comment by rixx** [comment]
And yeah, I'd import variations as separate products - no reason not to, really, just need to do the pretix style formatting of `'{product} – {variation}'` in the importer.

**Comment by raphaelm** [comment]
> It doesn't abort, it just writes a warning to stdout.

Oh, right. As this importer was written in August, I still don't see what we did at MRMCD, but I'm to lazy to research it in my backups either.
