### ISSUE TITLE
Neues Paket anlegen-Dialog

### ISSUE THREAD

**Issue by pc-coholic** [c3cashdesk/postix#35]
Since this is affecting only/mostly the German translation... As reported by @domke 

`/backoffice/supplies/create/` frägt nach `Anzahl von Produkten pro Paket` und `Art von Produkten im Paket`.

Laut Konvention wären die Produkte bspw. "Dauerbändchen", die Artikel eine Menge x eines Produkts.

Müsste der String daher nicht eigentlich `Anzahl von Artikeln pro Paket` lauten?

**Comment by raphaelm** [comment]
"Artikel" gibt es bisher nicht im Projekt, aber "Gegenstände" sollte es heißen. Artikel wäre rückblickend aber vllt sogar die hübschere Wortwahl gewesen
